In [1]:
import tensorflow as tf


In [27]:
matrix = tf.constant(4, shape = (3,1), dtype = float) # Sabit bir şekilde istenilen boyutlu isttenilen türlü bir matris oluşturduk.
print(matrix)

tf.Tensor(
[[4.]
 [4.]
 [4.]], shape=(3, 1), dtype=float32)


In [7]:
matrix = tf.eye(3) #Birim matris
print(matrix)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [9]:
matrix = tf.ones((4,3)) # 1 lik matris oluşturur.
print(matrix)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [10]:
matrix = tf.zeros((3,3,3)) # İstenilen boyutlarda 0 lık matrisler oluşturur.
print(matrix)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


In [11]:
matrix = tf.random.uniform((2,2), minval = 0 , maxval = 20) #İstenilen boyutlarda min ve max değeri verilerek o değerler arasında random değerli matris oluşturur.
print(matrix)

tf.Tensor(
[[11.067278  11.444793 ]
 [ 3.5103846 17.77405  ]], shape=(2, 2), dtype=float32)


In [12]:
matrix = tf.random.normal((3,3), mean = 0, stddev = 1) #Normal bir dağılımdan rastgele değerler verir.
print(tf.cast(matrix, dtype = tf.float64))

tf.Tensor(
[[-0.39284575 -1.93370283  0.00657964]
 [-0.05134608 -0.09399207  0.49842507]
 [-1.48965621  0.84721494 -0.77500236]], shape=(3, 3), dtype=float64)


In [17]:
matrix = tf.range(start = 0 , limit = 10, delta = 2)
print(matrix)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [18]:
matrix1 = tf.constant([1, 2, 3])
matrix2 = tf.constant([9, 8, 7])
matrix3 = tf.add(matrix1, matrix2)
print(matrix3)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [19]:
matrix3 = matrix1 + matrix2
print(matrix3)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [23]:
matrix1 = tf.constant([1, 2, 3])
matrix2 = tf.constant([9, 8, 7])
matrix3 = tf.subtract(matrix1, matrix2)
print(matrix3)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [25]:
matrix1 = tf.constant([1, 2, 3])
matrix2 = tf.constant([9, 8, 7])
matrix3 = tf.multiply(matrix1, matrix2)
print(matrix3)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [26]:
matrix1 = tf.constant([1, 2, 3])
matrix2 = tf.constant([9, 8, 7])
matrix3 = tf.divide(matrix1, matrix2)
print(matrix3)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
